version: "3.7"

services:
  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: my-custom-store-speedtest-tracker_server_1
      APP_PORT: 80
    
  server:
    environment:
      UID: 1000
      PGID: 1000
      TZ: Etc/UTC
      APP_KEY: base64:VoK57HhyhjZjDYAfUsueYfwL32KnSav6C/viiCzXrL0=
      DB_CONNECTION: sqlite
    image: lscr.io/linuxserver/speedtest-tracker:latest
    user: root
    volumes:
      - ${APP_DATA_DIR}/speedtest-tracker:/config
